version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_USERNAME: $DATABASE_USER
      MONGO_INITDB_PASSWORD: $DATABASE_PASSWORD
      MONGO_INITDB_DATABASE: $DATABASE_NAME
    ports:
      - $DATABASE_PORT:27017
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    depends_on:
      - "mongodb"
    ports:
      - $RABBIT_PORT:5672
      - $RABBIT_UI_PORT:15672

  # api:
  #   build: ./API
  #   command: bash -c "npm install && npm start"         
  #   restart: always
  #   depends_on:
  #     - "rabbitmq"
  #   network_mode: "host"
  #   volumes:
  #     - ./API:/node
  
  # scrapper:
  #   build: ./Scrapper
  #   command: bash -c "npm install && npm start"         
  #   restart: always
  #   depends_on:
  #     - "api"
  #   network_mode: "host"
  #   volumes:
  #     - ./Scrapper:/node

  # frontend:

